version: "3.9"
services:
  express:
    container_name: rss-node-template-express
    image: chocola/node-js-2021:latest
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.express
    networks:
      - user_network
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./logs:/usr/app/logs
      - ./src:/usr/app/src
      - /usr/app/node_modules
    restart: always
    depends_on:
      - postgres
  postgres:
    container_name: rss-node-template-posgres
    image: chocola/node-js-2021-posgres:latest
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.postgres
    networks:
      - user_network
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
    restart: always

networks:
  user_network:
    driver: bridge
